os: Visual Studio 2017

configuration: Release

before_build:
  - nuget restore

after_build:
  # Papercut
  - cd %APPVEYOR_BUILD_FOLDER%\src\Papercut.UI\bin\Release # md plugins
  - 7z a Papercut.%APPVEYOR_BUILD_VERSION%.zip plugins
  - 7z a Papercut.%APPVEYOR_BUILD_VERSION%.zip Papercut.exe
  - 7z a Papercut.%APPVEYOR_BUILD_VERSION%.zip Papercut.exe.*
  - 7z a Papercut.%APPVEYOR_BUILD_VERSION%.zip Readme.eml
  - appveyor PushArtifact Papercut.%APPVEYOR_BUILD_VERSION%.zip
  # Papercut Service
  - cd %APPVEYOR_BUILD_FOLDER%\src\Papercut.Service\bin\Release # md plugins
  - 7z a PapercutService.%APPVEYOR_BUILD_VERSION%.zip plugins  
  - 7z a PapercutService.%APPVEYOR_BUILD_VERSION%.zip Papercut.Service.*
  - 7z a PapercutService.%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\extras\Install-Papercut-Service.bat
  - 7z a PapercutService.%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\extras\Uninstall-Papercut-Service.bat
  - appveyor PushArtifact PapercutService.%APPVEYOR_BUILD_VERSION%.zip
  # Papercut Installer bundle
  - cd %APPVEYOR_BUILD_FOLDER%\src\Papercut.Bootstrapper\bin\Release 
  - appveyor PushArtifact Papercut.Setup.exe
  - cd %APPVEYOR_BUILD_FOLDER%
  # Chocolately
  - nuget pack chocolately\Papercut.nuspec -version %APPVEYOR_BUILD_VERSION%
  - appveyor PushArtifact Papercut.%APPVEYOR_BUILD_VERSION%.nupkg
